# Generated by Django 4.0.8 on 2023-01-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questions',
            table='AV_QUESTIONS',
        ),
    ]
