# Generated by Django 4.0.8 on 2023-01-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0005_remove_regimes_question_regimes_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='regimes',
            name='is_deleted',
            field=models.BooleanField(blank=True, default='False'),
        ),
    ]
